import "styles/global.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body>
        <div className="w-screen h-screen flex justify-center bg-neutral-900 overflow-hidden">
          {children}
        </div>
      </body>
    </html>
  );
}
